### ISSUE TITLE
Is is possible using category rather than Inheritance

### ISSUE THREAD

**Issue by beforeold** [tingxins/InputKit#2]
TXLimitTextField is cool, thanks for saving me from struggling.

one question as the issue title.

**Comment by tingxins** [comment]
Yep. First, thanks for your cool @beforeold .  Well, it’s a good idea. but I have considered Category ever. for some reasons. I implemented InputKit with Inheritance. sometimes, especially in some projects. I think it’s unnecessary to limits users input contents somewhere. not like BlocksKit, it’s defines as category. But InputKit defines as a component. if you want to use InputKit. Just Inherit it. if not. nothing will happens. 🐵

**Comment by beforeold** [comment]
Gotcha.
