### ISSUE TITLE
跟ReactiveCocoa有冲突，具体看Demo

### ISSUE THREAD

**Issue by devcxm** [tingxins/InputKit#3]
[TestInputKit.zip](https://github.com/tingxins/InputKit/files/1147837/TestInputKit.zip)

**Comment by tingxins** [comment]
此问题是因为在使用 `TXLimitedTextView` 时，由于 `RAC ` 与 `InputKit ` 消息转发存在不兼容导致，但`TXLimitedTextField ` 不会存在此问题（跟RAC的内部实现有关）。`InputKit ` **v1.1.3** 中的 `TXLimitedTextView ` **已兼容** `RAC `，并修复此问题。使用如下：

为 `TXLimitedTextView ` 增添了一个属性 **compatibleWithRAC**，如果在项目中使用了 `RAC `，设置该属性为 **YES** 即可解决此冲突。详见 README.md 😄
