### ISSUE TITLE
楼主！！！IQKeyBroad blocksKit 把键盘收下去就崩溃了。比较急，在线等\doge

### ISSUE THREAD

**Issue by Meterwhite** [tingxins/InputKit#31]
textFieldDidEndEditing:reason: 这个selector

<img width="1175" alt="图片" src="https://user-images.githubusercontent.com/9498919/65229810-779ffc80-daff-11e9-9db4-1ebf99dcfbf5.png">

<img width="1156" alt="图片" src="https://user-images.githubusercontent.com/9498919/65229891-91414400-daff-11e9-9c1b-3c2ec94cd484.png">

<img width="252" alt="图片" src="https://user-images.githubusercontent.com/9498919/65230045-cb124a80-daff-11e9-8b76-8e7bb24540bb.png">

**Comment by tingxins** [comment]
可以参考下这篇[文章](http://tingxins.cn/2017/07/01/about-delegate-oc/)，这个应该是消息转发出现问题

**Comment by Meterwhite** [comment]
感谢楼主的答复，昨天已经把blockskit扔掉了😃，其实也就用它几个方法，问题还那么多。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: tingxins <notifications@github.com>
发送时间: Friday, September 20, 2019 6:52:10 PM
收件人: tingxins/InputKit <InputKit@noreply.github.com>
抄送: Meterwhite <quxingyi@outlook.com>; Author <author@noreply.github.com>
主题: Re: [tingxins/InputKit] 楼主！！！IQKeyBroad blocksKit 把键盘收下去就崩溃了。比较急，在线等\doge (#31)


可以参考下这篇文章<http://tingxins.cn/2017/07/01/about-delegate-oc/>，这个应该是消息转发出现问题
