### ISSUE TITLE
Emojis get torn apart at the last limited index.

### ISSUE THREAD

**Issue by ShannonChenCHN** [tingxins/InputKit#7]
输入 emoji 表情时，出现异常：
假设限制输入 10 个字符, 第 10 个字符如果输入是 emoji , 则 emoji 显示异常，如图。

<img src='https://user-images.githubusercontent.com/15443132/30508912-0bd9ea7c-9ad5-11e7-94a1-fd1937941bb6.png' width=375 height=667/>

**Comment by tingxins** [comment]
Perfect.
